---
- name: NewsCred dev docker setup
  hosts: localhost
  connection: local
  gather_facts: False

  pre_tasks:
    - include_vars: vars.yml

  roles:
    - git
    - vscode
    - chrome
    - { role: jdk, jdk_version: 9 }
    - docker
    - npm
    - { role: mysql, version: 5.6 }
    - { role: mongodb, version: 3.0.8 }
