---
- name: NewsCred dev docker setup
  hosts: localhost
  connection: local
  gather_facts: False

  pre_tasks:
    - include_vars: vars.yml

  roles:
    - git
    - vscode
    - chrome
    - { role: jdk, version: 14 }
    - docker
    - role: ansible-role-nvm
      nodejs_version: "12.13.0"
      nvm_commands:
       - "nvm exec default npm install"
    - debian-packages
