---
- name: copy .newscred.yaml to home directory
  template:
    src: files/newscred.yaml
    dest: {{home}}/.newscred.yaml

- git:
    repo: 'git@github.com:newscred/localdev.git'
    dest: {{workspace}}
    version: master
