---
- name: Install git
  apt: name=git state=installed

- git_config:
    name: user.name
    scope: global
    value: '{{git_config.user.name}}'

- git_config:
    name: user.email
    scope: global
    value: '{{git_config.user.email}}'

# set alias
- git_config:
    name: alias.st
    scope: global
    value: status

- git_config:
    name: alias.co
    scope: global
    value: checkout
