---
- name: Install git
  apt: name=git state=installed

- git_config:
    name: user.name
    scope: global
    value: A.K.M. Ashrafuzzaman

- git_config:
    name: user.email
    scope: global
    value: ashrafuzzaman.g2@gmail.com

# set alias
- git_config:
    name: alias.st
    scope: global
    value: status

- git_config:
    name: alias.co
    scope: global
    value: checkout
