---
- stat:
    path: /usr/bin/npm
  register: npm

- name: Add npm package in apt list 
  shell: curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  when: npm|failed

- apt:
    name: nodejs
    state: present
    update_cache: yes
  when: npm|failed
