---
- apt_repository:
    repo: ppa:webupd8team/java
    state: present

- name: Accept Java License
  become: yes
  debconf:
    name: 'oracle-java{{version}}-installer'
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: 'select'

- name: Install Oracle Java
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - 'oracle-java{{version}}-installer'
    - ca-certificates
    - 'oracle-java{{version}}-set-default'
