---
- stat:
    path: ~/.rvm/scripts/rvm
  register: rvm
 
- name: Install rvm 
  shell: \curl -sSL https://get.rvm.io | bash
  when: rvm|failed

- name: Source rvm
  sudo: no
  shell: source ~/.rvm/scripts/rvm executable=/bin/bash

- name: Check ruby version
  shell: 'rvm list | grep {{version}}'
  register: ruby_installed

- name: Install ruby 
  shell: 'rvm install {{version}}'
  when: ruby_installed|failed
